<?
  return [  
    'Assets'=>[
      ['Module/Depends',
        'Pack',
      ],
    //['Cpp/Define', '_OFF_T_DEFINED',],
      ['Cpp/Define', '_CONSOLE',],
      ['Cpp/Define', 'UNICODE',],
      ['Cpp/Define', '_UNICODE',],
      ['Cpp/Define', '_CRT_SECURE_NO_DEPRECATE',],
      ['Cpp/Compiler', 'Win32', 'VC'=>2017, 'Debug'],
      ['Sub', // Compiler libs
        ['Cpp/LibPath', '>Compiler',],
        ['Cpp/Lib'     ,
          'version.lib',
          'Rpcrt4.lib',
        ],
      ],
      ['Sub', //libs
        ['Module/Path' ,'../Pack'],
        ['Cpp/LibPath' ,'Build/thirdparty/lib'],
        ['Public'],
        ['Cpp/Lib'     ,
          'libjpeg.lib' ,
          'libpng.lib'  ,
          'zlib.lib'    , // TODO: Remove
        ],
        ['Cpp/Include' ,'Src/thirdparty/libpng' ],
        ['Cpp/Include' ,'Src/thirdparty/jpeg'   ],
        ['Cpp/Include' ,'Src/thirdparty/wtl'    ], // TODO: Remove
        ['Cpp/Include' ,'Src/thirdparty/zlib'   ], // TODO: Remove
      ],
      ['Sub',
        ['Module/Path' ,'../Pack/Src/reporting/crashrpt'],
        ['Cpp/SrcPath' ,''],
        ['Public'],
        ['Cpp/Include' ,''],
        ['Cpp/Src'     ,
          'Utility.cpp',
        ],
      ],
      ['Sub',
        ['Module/Path' ,'../Pack/Src/reporting/crashsender'],
        ['Cpp/SrcPath' ,''],
        ['Public'],
        ['Cpp/Include' ,''],
        ['Cpp/Src'     ,
          'ScreenCap.cpp',
        ],
      ],
      ['Exec/Option:link',
        '>Remove'=>[
          '/NODEFAULTLIB',
        ],
        '/SUBSYSTEM:'=>'CONSOLE',
      ],
      ['Cpp/SrcPath' ,''],
    //['Cpp/Manifest', 'DeclareDPIAware.manifest'],
      ['Public'],
      ['Cpp/MakeExe', '>Sub'=>['Cpp/Src'=>'main.cpp',], 'Name'=>'TakeScreen'],
      ['Target/Copy' ,'From'=>'Bin/Exe'     ,'To'=>'',],
    ],
  ];
?>